server.port=8090
logging.level.guru.springframework=debug
# Liste des stratégies activées (séparées par une virgule)
trading.strategies.enabled=EmaCrossoverStrategy,BreakoutStrategy
# Liste des filtres activés (séparés par une virgule)
trading.filters.enabled=TrendFilter,VolumeFilter,VolatilityFilter
# Pondération des filtres (ex: TrendFilter = 15, VolumeFilter = 10, VolatilityFilter = 5)
trading.filters.weights.TrendFilter=15
trading.filters.weights.VolumeFilter=10
trading.filters.weights.VolatilityFilter=5
# Configuration de la base SQLite
#spring.datasource.url=jdbc:sqlite:/home/ronan/Documents/FinancialProject/Financial-Project/sqlite.db
#spring.datasource.username=sa
#spring.datasource.password=sa
#spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
#spring.datasource.driver-class-name=org.sqlite.JDBCs
spring.jpa.hibernate.ddl-auto=create-drop
hibernate.hbm2ddl.auto=create-drop
#hibernate.show_sql=true
# Activer le logging des requêtes SQL
#spring.jpa.show-sql=true
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
# Désactiver les contrôles transactionnels avancés (SQLite ne supporte pas certaines features)
#spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
hibernate.boot.allow_jdbc_metadata_access=true
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/restdb
spring.datasource.username=restadmin
spring.datasource.password=ronanronan77
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# HikariCP Configuration
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.leak-detection-threshold=2000

#MARKETSTACK API
marketstack.api.url=https://api.marketstack.com/v1
marketstack.api.key=68d412d015ba4070cf6d5f2d4e6485cc

#CURRENCYLAYER API
currencylayer.api.url=https://api.currencylayer.com
currencylayer.api.key=5daea80517a8588351c8e61011b7aaf8

nasdaq.api.key=zqNMxPjE-nTvSaba2jZz