server.port=8090
logging.level.guru.springframework=debug
# Liste des stratégies activées (séparées par une virgule)
trading.strategies.enabled=EmaCrossoverStrategy,BreakoutStrategy
# Liste des filtres activés (séparés par une virgule)
trading.filters.enabled=TrendFilter,VolumeFilter,VolatilityFilter
# Pondération des filtres (ex: TrendFilter = 15, VolumeFilter = 10, VolatilityFilter = 5)
trading.filters.weights.TrendFilter=15
trading.filters.weights.VolumeFilter=10
trading.filters.weights.VolatilityFilter=5
# Configuration de la base SQLite
spring.datasource.url=jdbc:sqlite:/home/ronan/Documents/FinancialProject/Financial-Project/sqlite.db
spring.datasource.hikari.maximum-pool-size=1
spring.datasource.username=sa
spring.datasource.password=sa
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.hibernate.ddl-auto=update
hibernate.hbm2ddl.auto=create-drop
hibernate.show_sql=true
# Activer le logging des requêtes SQL
spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
# Désactiver les contrôles transactionnels avancés (SQLite ne supporte pas certaines features)
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false
