app:
  live:
    ingest:
      hmacEnabled: false
      hmacHeader: X-Live-Hmac
      hmacSecretEnv: LIVE_HMAC_SECRET
    sse:
      heartbeatMillis: 15000
spring:
  flyway:
    enabled: false
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    prometheus:
      enabled: true
  metrics:
    tags:
      application: financial-project
delta:
  #base-uri: ${DELTA_BASE_URI:./delta-tables}
  base-uri: ${DELTA_BASE_URI:s3a://quant-delta-dev/delta}
ibkr:
  host: 127.0.0.1
  port: 7497
  client-id: 101
  connect-timeout-millis: 10000
  pacing-min-interval-millis: 1200
  pacing-violation-backoff-millis: 5000
  default-request-timeout-millis: 8000
dukascopy:
  jnlp-url: ${DUKASCOPY_JNLP_URL:http://platform.dukascopy.com/demo_3/jforex_3.jnlp}
  #username: ${DUKASCOPY_USERNAME:Espe20}
  #password: ${DUKASCOPY_PASSWORD:EwqMf7w8JJN7Lay)}
  username: ${DUKASCOPY_USERNAME:DEMO2MpUmT}
  password: ${DUKASCOPY_PASSWORD:MpUmT}
  connect-timeout-millis: 15000
  history-timeout-millis: 30000
  offer-side: BID

external:
  coingecko:
    base-url: https://api.coingecko.com/api/v3
    api-key: ${COINGECKO_API_KEY:demo}   # var d'env, ne JAMAIS commiter la vraie clé

  fmp:
    base-url: https://financialmodelingprep.com/api/v3
    api-key: ${FMP_API_KEY:demo}

  eodhd:
    base-url: https://eodhd.com/api/eod
    api-key: ${EODHD_API_KEY:demo}

