ALTER TABLE market_stats
    ADD COLUMN IF NOT EXISTS p_mean DOUBLE NULL,
    ADD COLUMN IF NOT EXISTS p_map DOUBLE NULL,
    ADD COLUMN IF NOT EXISTS hdi_low DOUBLE NULL,
    ADD COLUMN IF NOT EXISTS hdi_high DOUBLE NULL,
    ADD COLUMN IF NOT EXISTS lift_freq DOUBLE NULL,
    ADD COLUMN IF NOT EXISTS lift_bayes DOUBLE NULL,
    ADD COLUMN IF NOT EXISTS p_value DOUBLE NULL,
    ADD COLUMN IF NOT EXISTS q_value DOUBLE NULL,
    ADD COLUMN IF NOT EXISTS significant BOOLEAN NULL,
    ADD COLUMN IF NOT EXISTS insufficient BOOLEAN NULL;
